### ISSUE TITLE
Configuring Directus to run in a subdirectory

### ISSUE THREAD

**Issue by kitschpatrol** [platformsh-templates/directus#40]
Thanks for providing this template!

I'm trying to adapt it for a slightly different use-case, and am hitting a wall. I'd like Directus to be accessible under a `/directus` subdirectory, so it can run alongside some other applications in a single platform.sh configuration.

I've set up my `routes.yml` like this:
```
https://{default}/directus:
  type: upstream
  upstream: directus:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['*']
    headers: ['Accept', 'Accept-Language']

https://{default}/:
  type: upstream
  upstream: blog:http
```

The `.platform.app.yaml` configuration is basically identical to the one provided in this repository.

I've played with some different settings for the `web.locations` key in the `.platform.app.yaml` configuration, but no matter what I always get this error when trying to access Directus through the subdirectory:

```
{
  "errors": [
    {
      "message": "Route /directus doesn't exist.",
      "extensions": {
        "code": "ROUTE_NOT_FOUND"
      }
    }
  ]
}
```

I've made sure that the `PUBLIC_URL` environment variable is set correctly, and also tried setting the `ROOT_REDIRECT` to explicitly factor in the subdirectory, but no dice.

I've confirmed that Directus works normally on Platform.sh if I put it on the `/` route in `routes.yml` instead, so the problem is reasonably isolated to the subdirectory route.

I've also confirmed that this basic formula for routing specific subdirectories to specific apps in Platform.sh usually works fine. 

Read up on a few other issues, which seem to point to nuances of configuring the proxy / redirect, but nothing specifically actionable:
- https://github.com/directus/directus/discussions/3174
- https://github.com/directus/directus/discussions/3904

I'm about to dig into the nginx configurations Platform.sh is generating, but any advice here would be appreciated!

**Comment by kitschpatrol** [comment]
Ok I've think I got it based on the conversation here: https://github.com/directus/directus/discussions/4480

In addition to setting the route in `routes.yml` and the `PUBLIC_URL` variable, you also need an explicit rewrite rule in the `.platform.app.yaml` web configuration:

```
  web: 
    commands:
      start: npx directus start
    locations:
      '/directus':
        rules:    
          '^/directus/(?<path>.*)$':
            passthru: '/$path'
```
